#!/bin/bash 

# create script wrapper to activate base environment
#CODE_ROOT="/proj/MDTF-diagnostics" #TODO MOVE TO DOCKERFILE AS ENV
_CONDA_WRAPPER="$CODE_ROOT/mdtf"

source activate _MDTF_base

if [ -e "$_CONDA_WRAPPER" ]; then
    rm -f "$_CONDA_WRAPPER"
fi
echo '#!/usr/bin/env bash' > "$_CONDA_WRAPPER"
echo 'CODE_ROOT=$CODE_ROOT' > "$_CONDA_WRAPPER"
echo "# This wrapper script is generated by conda_env_setup.sh." >> "$_CONDA_WRAPPER"
echo "pushd \"\$CODE_ROOT\" > /dev/null" >> "$_CONDA_WRAPPER"
echo "/usr/bin/env python -m src.mdtf \"\$@\"" >> "$_CONDA_WRAPPER"
echo "popd > /dev/null" >> "$_CONDA_WRAPPER"
chmod +x "$_CONDA_WRAPPER"
echo "Created MDTF wrapper script at ${_CONDA_WRAPPER}"

# trivial check that install script worked
.$CODE_ROOT/mdtf --version
bash
