name: CI
on:
  push:
    branches: [ aradhakrishnanGFDL-patch5 ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/c6h4h4s8/mdtf/mdtf-test:latest
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - name: Check PATH
        run: (echo $PATH) || (echo "No path")
