name: docker-run-minitest
on:
  pull_request:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/c6h4h4s8/mdtf/mdtf-test:latest
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
      - name: Activate environment
        run: (micromamba activate; micromamba activate _MDTF_base)
      - name: Get version of mdtf_framework.py 
        run: (mdtf_framework.py --version)
